<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('stuntcoders_simplemenu')->__('Add Category'); ?></h4>
    </div>
    <div class="fieldset fieldset-wide">
        <div class="hor-scroll">
            <div id="label-category" class="checkbox-list">
                <?php foreach(Mage::helper('stuntcoders_simplemenu')->getCategoriesArray() as $categoryId => $categoryData): ?>
                    <label class="level-<?php echo $categoryData['level']?>">
                        <input type="checkbox" name="checkbox" value="<?php echo $categoryId?>">
                        <?php echo isset($categoryData['name']) ? $categoryData['name'] : ""; ?>
                    </label><br/>
                <?php endforeach; ?>
            </div>
            <button id="add-category"><?php echo Mage::helper('stuntcoders_simplemenu')->__('Add') ?></button>
        </div>
    </div>
</div>
