<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">
            <?php echo Mage::helper('stuntcoders_simplemenu')->__('Add CMS Page'); ?>
        </h4>
    </div>
    <div class="fieldset fieldset-wide">
        <div class="hor-scroll">
            <div id="label-cms" class="checkbox-list">
                <?php

                foreach (Mage::getModel('cms/page')->getCollection() as $cmsPage) {
                    echo "<label>"
                        . "<input type='checkbox' name='checkbox' value='{$cmsPage['page_id']}'>"
                        . $cmsPage['title']
                        . "</label><br/>";
                }

                ?>
            </div>
            <button id="add-cms"><?php echo Mage::helper('stuntcoders_simplemenu')->__('Add') ?></button>
        </div>
    </div>
</div>
