<?php
$menu = array();
if (Mage::registry('simplemenu_data')) {
    $menuData = Mage::registry('simplemenu_data')->getData();
    if (!empty($menuData['value'])) {
        $menu = json_decode($menuData['value'], true);
    }
}
?>
<?php
function echoMenuItems(array $menu)
{
    foreach ($menu as $menuItem) {
        switch((int) $menuItem['type'])
        {
            case Stuntcoders_Simplemenu_Model_Simplemenu::MENU_ITEM_TYPE_CATEGORY:
                $itemTypeName = Mage::helper('stuntcoders_simplemenu')->__('Category') . " (ID: {$menuItem['id']})";
                break;
            case Stuntcoders_Simplemenu_Model_Simplemenu::MENU_ITEM_TYPE_CMS_PAGE:
                $itemTypeName = Mage::helper('stuntcoders_simplemenu')->__('Cms page') . " (ID: {$menuItem['id']})";
                break;
            case Stuntcoders_Simplemenu_Model_Simplemenu::MENU_ITEM_TYPE_SPECIAL:
                $itemTypeName = Mage::helper('stuntcoders_simplemenu')->__('%s page', $menuItem['typename']);
                break;
            default:
                break;
        }
        ?>
        <li class="dd-item"
            data-type="<?php echo $menuItem['type']?>"
            data-label="<?php echo $menuItem['label']?>"
            <?php echo Mage::helper('stuntcoders_simplemenu')->getMenuItemDataUrl($menuItem); ?>
            <?php echo Mage::helper('stuntcoders_simplemenu')->getMenuItemDataTypeName($menuItem); ?>
            <?php echo Mage::helper('stuntcoders_simplemenu')->getMenuItemDataSubcategories($menuItem); ?>
            <?php echo Mage::helper('stuntcoders_simplemenu')->getMenuItemDataId($menuItem); ?>>
            <div class="dd-handle">
                <?php echo $menuItem['label']?>
            </div>
            <div class="dd-fields">
                <div>
                    <?php echo Mage::helper('stuntcoders_simplemenu')->__('Label: '); ?>
                    <input type="text" value = "" class="dd-field-label">
                </div>
                <?php if ((int) $menuItem['type'] === 2): ?>
                    <div>
                        <?php echo Mage::helper('stuntcoders_simplemenu')->__('Depth of subcategories to load'); ?>
                        <input type="text" value = "" class="dd-field-subcategories">
                    </div>
                <?php endif; ?>
                <?php if ((int) $menuItem['type'] === 1): ?>
                    <div>
                        <?php echo Mage::helper('stuntcoders_simplemenu')->__('Url: '); ?>
                        <input type="text" value = "" class="dd-field-url">
                    </div>
                <?php endif; ?>
                <?php if ((int) $menuItem['type'] !== 1): ?>
                    <div>
                        <?php echo Mage::helper('stuntcoders_simplemenu')->__('Type: ') . $itemTypeName?>
                    </div>
                <?php endif; ?>
            </div>
            <span class="dd-options">
                <a href="#" class="dd-edit"><?php echo Mage::helper('stuntcoders_simplemenu')->__('Edit'); ?></a>
                <a href="#" class="dd-delete"><?php echo Mage::helper('stuntcoders_simplemenu')->__('Delete'); ?></a>
            </span>
            <?php if (isset($menuItem['children'])): ?>
                <ol class="dd-list">
                    <?php echoMenuItems($menuItem['children']); ?>
                </ol>
            <?php endif; ?>
        </li>
    <?php
    }
}
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">
            <?php echo Mage::helper('stuntcoders_simplemenu')->__('Menu Items'); ?>
        </h4>
    </div>
    <div class="fieldset fieldset-wide">
        <div class="hor-scroll">
            <div class="dd">
                <ol class="dd-list">
                    <?php echoMenuItems($menu); ?>
                </ol>
            </div>
        </div>
    </div>
</div>
