<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('stuntcoders_simplemenu')->__('Add Link'); ?></h4>
    </div>
    <div class="fieldset fieldset-wide">
        <div class="hor-scroll">
            <div class="link-input-field">
                <label for="label-link">
                    <?php echo Mage::helper('stuntcoders_simplemenu')->__('Label: '); ?>
                </label>
                <input type="text" id="label-link" value=""
                       placeholder="<?php echo Mage::helper('stuntcoders_simplemenu')->__('Label'); ?>"
                >
            </div>
            <div class="link-input-field">
                <label for="url-link">
                    <?php echo Mage::helper('stuntcoders_simplemenu')->__('Url: '); ?>
                </label>
                <input type="text" id="url-link" value=''
                       placeholder="<?php echo Mage::helper('stuntcoders_simplemenu')->__('Url'); ?>"
                >
            </div>
            <div>
                <button id="add-link">
                    <?php echo Mage::helper('stuntcoders_simplemenu')->__('Add'); ?>
                </button>
            </div>
        </div>
    </div>
</div>
