<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">
            <?php echo Mage::helper('stuntcoders_simplemenu')->__('Add Special Page'); ?>
        </h4>
    </div>
    <div class="fieldset fieldset-wide">
        <div class="hor-scroll">
            <div id="label-special" class="checkbox-list">
                <?php

                foreach (Stuntcoders_Simplemenu_Model_Simplemenu_Special::getPagesArray() as $id => $name) {
                    echo "<label>"
                        . "<input type='checkbox' name='Login' value='{$id}'>"
                        . Mage::helper('stuntcoders_simplemenu')->__($name)
                        . "</label><br/>";
                }

                ?>
            </div>
            <button id="add-special"><?php echo Mage::helper('stuntcoders_simplemenu')->__('Add') ?></button>
        </div>
    </div>
</div>
