<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">
            <?php echo Mage::helper('stuntcoders_simplemenu')->__('Add Special Page'); ?>
        </h4>
    </div>
    <div class="fieldset fieldset-wide">
        <div class="hor-scroll">
            <div id="label-special" class="checkbox-list">
                <label>
                    <input type="checkbox" name="Login" value="1">
                    <?php echo Mage::helper('stuntcoders_simplemenu')->__('Login') ?>
                </label><br/>
                <label>
                    <input type="checkbox" name="Logout" value="2">
                    <?php echo Mage::helper('stuntcoders_simplemenu')->__('Logout') ?>
                </label><br/>
                <label>
                    <input type="checkbox" name="checkbox" value="3">
                    <?php echo Mage::helper('stuntcoders_simplemenu')->__('Cart') ?>
                </label><br/>
                <label>
                    <input type="checkbox" name="checkbox" value="4">
                    <?php echo Mage::helper('stuntcoders_simplemenu')->__('Checkout') ?>
                </label><br/>
                <label>
                    <input type="checkbox" name="checkbox" value="5">
                    <?php echo Mage::helper('stuntcoders_simplemenu')->__('Wishlist') ?>
                </label><br/>
            </div>
            <button id="add-special"><?php echo Mage::helper('stuntcoders_simplemenu')->__('Add') ?></button>
        </div>
    </div>
</div>
