<div id="menu-item-template" style="display:none">
    <li class="dd-item">
        <div class="dd-handle">
            {label}
        </div>
        <div class="dd-fields">
            {fields}
        </div>
            <span class="dd-options">
                <a href="#" class="dd-edit"><?php echo Mage::helper('stuntcoders_simplemenu')->__('Edit'); ?></a>
                <a href="#" class="dd-delete"><?php echo Mage::helper('stuntcoders_simplemenu')->__('Delete'); ?></a>
            </span>
    </li>
</div>

<div id="menu-item-template-fields-link" style="display:none">
    <div>
        <?php echo Mage::helper('stuntcoders_simplemenu')->__('Label: '); ?>
        <input type="text" value = "" class="dd-field-label">
    </div>
    <div>
        <?php echo Mage::helper('stuntcoders_simplemenu')->__('Url: '); ?>
        <input type="text" value = "" class="dd-field-url">
    </div>
</div>

<div id="menu-item-template-fields-category" style="display:none">
    <div>
        <?php echo Mage::helper('stuntcoders_simplemenu')->__('Label: '); ?>
        <input type="text" value = "" class="dd-field-label">
    </div>
    <div>
        <?php echo Mage::helper('stuntcoders_simplemenu')->__('Depth of subcategories to load'); ?>
        <input type="text" value = "" class="dd-field-subcategories">
    </div>
    <div>
        <?php echo Mage::helper('stuntcoders_simplemenu')->__('Category') ?> (ID: <label class="dd-field-id"></label>)
    </div>
</div>

<div id="menu-item-template-fields-cms" style="display:none">
    <div>
        <?php echo Mage::helper('stuntcoders_simplemenu')->__('label: '); ?>
        <input type="text" value = "" class="dd-field-label">
    </div>
    <div>
        <?php echo Mage::helper('stuntcoders_simplemenu')->__('Cms page') ?> (ID: <label class="dd-field-id"></label>)
    </div>
</div>

<div id="menu-item-template-fields-special" style="display:none">
    <div>
        <?php echo Mage::helper('stuntcoders_simplemenu')->__('Label: '); ?>
        <input type="text" value = "" class="dd-field-label">
    </div>
    <div>
        <?php echo Mage::helper('stuntcoders_simplemenu')->__('Type: '); ?>
        <label class="dd-field-typename"></label> <?php echo Mage::helper('stuntcoders_simplemenu')->__('page') ?>
    </div>
</div>
